[workspace]
members = [
    "skar",
    "format",
    "rpc-client",
    "rpc-types",
]

[workspace.dependencies]
async-std = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
futures = "0.3"
log = "0.4"
serde_json = "1"
