[http_server]
addr = "127.0.0.1:1131"
response_size_limit_mb = 30
response_time_limit_ms = 5000

[db]
path = "data/db"

[ingest]
from_block = 0
to_block = 18000000
concurrency_limit = 8
batch_size = 100

[parquet]
path = "data/parquet"

[parquet.blocks]
max_file_size = 100000
max_row_group_size = 10000
data_page_size_limit = 1024000

[parquet.transactions]
max_file_size = 100000
max_row_group_size = 10000
data_page_size_limit = 1000000

[parquet.logs]
max_file_size = 100000
max_row_group_size = 10000
data_page_size_limit = 1000000

[ingest.rpc_client]
http_req_timeout_millis = 5000

[[ingest.rpc_client.endpoints]]
url = "https://rpc.ankr.com/eth"
status_refresh_interval_secs = 10
req_limit = 10
req_limit_window_ms = 1000
get_logs_range_limit = 100
batch_size_limit = 100
