[package]
name = "skar-ingest"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
futures = "0.3"
ethbloom = "0.13"

skar-format = { path = "../format" }
skar-rpc-client = { path = "../rpc-client" }
